import Form from "@/components/form";
import Phone from "@/components/phone";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const handleViewProfile = () => {
    router.push("/profile");
  };

  return (
    <>
      <Head>
        <title>iRecreate Linktree</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed bottom-4 lg:top-8 lg:bottom-auto right-4 lg:right-8 scale-75 lg:scale-100">
        <button
          onClick={handleViewProfile}
          className="bg-purple-600 text-purple-100 font-bold py-2 px-6 rounded hover:ring-4 hover:ring-purple-300 transition-all duration-150 text-sm"
        >
          View Profile
        </button>
      </div>

      <div className="container mx-auto py-10 lg:py-20 px-8 grid grid-cols-1 gap-16 md:grid-cols-2">
        <Form />
        <Phone />
      </div>
    </>
  );
}
